*.testmy.net
*.pandasecurity.com
*.windows.net
*.devo.com
*.pandasoftware.com
*.ivanti.com
*.ctmail.com
*.threatseeker.com
*.globalsign.net
*.globalsign.com
*.digicert.com
*.sectigo.com
*.microsoft.com
*.windowsupdate.com
*.verisign.com
*.symcb.com
*.symcd.com
*.msftncsi.com
*.public-trust.com
*.iana.org
*.tenable.com
*.watchguard.com
*.httpbin.org
*.forcepoint.com
